controller_list:
  - name: fake_a_bot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - a_bot_shoulder_pan_joint
      - a_bot_shoulder_lift_joint
      - a_bot_elbow_joint
      - a_bot_wrist_1_joint
      - a_bot_wrist_2_joint
      - a_bot_wrist_3_joint
  - name: fake_a_bot_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - a_bot_finger_joint
initial:  # Define initial robot poses per group
  - group: a_bot_arm
    pose: home
  - group: a_bot_gripper
    pose: closed