version: '3.9'
services:
  ros:
    image: thbarkouki/homestri-ur5e-robotiq2f85:latest
    command: tail -F anything
    #command: /bin/bash -c "source /catkin_ws/docker-entrypoint.sh && roslaunch moveit_config demo.launch"
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
    ports:
      - "50001-50004:50001-50004"
      - "54321"
    # logging: # uncomment to hide the logs
    #   driver: none 

  novnc:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=958
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:
  # http://localhost:8080/vnc_auto.html