<?xml version="1.0"?>

<!-- This macro adds a convenient TF frame at the tip of the closed gripper. -->
<!-- The position of the TF frame has not been measured at all and needs to be calibrated. -->

<robot name="environment_homestri" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="environment" params="pedestal_height:=0.2">

    <!-- robotiq coupling link -->
    <link name="pedestal">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 ${-pedestal_height/2}"/>
        <geometry>
          <cylinder length="${pedestal_height}" radius="0.2"/>
        </geometry>
        <material name="grey">
            <color rgba=".5 .5 .5 1"/>
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${-pedestal_height/2}"/>
        <geometry>
          <cylinder length="${pedestal_height}" radius="0.2"/>
        </geometry>
      </collision>
    </link>

    <link name="table">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0.01" />
            <geometry>
                <box size="3 3 0.02" />
            </geometry>
            <material name="grey">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.01"/>
            <geometry>
                <box size="3 3 0.02" />
            </geometry>
        </collision>
    </link>

    <joint name="pedestal_to_table" type="fixed">
        <parent link="table"/>
        <child link="pedestal"/>
        <origin xyz="0 0 ${pedestal_height+0.02}" />
    </joint>


  </xacro:macro>
</robot>
