<?xml version="1.0"?>

<!-- This macro adds a convenient TF frame at the tip of the closed gripper. -->
<!-- The position of the TF frame has not been measured at all and needs to be calibrated. -->

<robot name="robotiq_2f_85"
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="robotiq_2f_85" params="prefix parent transmission_hw_interface coupling_width:=0.01 *origin">

    <!-- Spawn and attach robotiq 85 gripper -->
    <xacro:include filename="$(find robotiq_2f_85_gripper_visualization)/urdf/robotiq_arg2f_85_macro.xacro" />
    <xacro:robotiq_arg2f_85 prefix="${prefix}" transmission_hw_interface="${transmission_hw_interface}" />
    <joint name="${prefix}robotiq_85_base_joint" type="fixed">
      <parent link="${prefix}robotiq_85_coupling" />
      <child link="${prefix}robotiq_arg2f_base_link" />
      <origin xyz="${coupling_width} 0 0" rpy="${pi} ${-pi/2} 0" />
    </joint>

    <!-- robotiq coupling link -->
    <link name="${prefix}robotiq_85_coupling">
      <visual>
        <origin rpy="0 ${pi/2} 0" xyz="${coupling_width/2} 0 0" />
        <geometry>
          <cylinder length="${coupling_width}" radius="0.0375" />
        </geometry>
        <material name="black">
          <color rgba=".1 .1 .1 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="0 ${pi/2} 0" xyz="${coupling_width/2} 0 0" />
        <geometry>
          <cylinder length="${coupling_width}" radius="0.0375" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}robotiq_85_coupling_joint" type="fixed">
      <parent link="${parent}" />
      <child link="${prefix}robotiq_85_coupling" />
      <xacro:insert_block name="origin" />
    </joint>

    <!-- ############ GAZEBO PROPERTIES ############ -->

    <gazebo>
      <!-- Mimic joints plugin-->
      <plugin filename="libroboticsgroup_upatras_gazebo_mimic_joint_plugin.so" name="${prefix}mimic_robotiq_85_5">
        <joint>${prefix}finger_joint</joint>
        <mimicJoint>${prefix}right_finger_joint</mimicJoint>
        <multiplier>1.0</multiplier>
        <hasPID/>
      </plugin>
    </gazebo>

    <xacro:macro name="robotiq_2f_85_gazebo_link_properties" params="reference material">
      <gazebo reference="${reference}">
        <material>${material}</material>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.16</mu1>
        <mu2>1.16</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.001</minDepth>
      </gazebo>
    </xacro:macro>

    <!-- Links colors  -->
    <xacro:robotiq_2f_85_gazebo_link_properties reference="${prefix}robotiq_arg2f_base_link" material="Gazebo/Black" />
    <xacro:robotiq_2f_85_gazebo_link_properties reference="${prefix}left_outer_knuckle" material="Gazebo/Grey" />
    <xacro:robotiq_2f_85_gazebo_link_properties reference="${prefix}left_outer_finger" material="Gazebo/Black" />
    <xacro:robotiq_2f_85_gazebo_link_properties reference="${prefix}left_inner_finger" material="Gazebo/Grey" />
    <xacro:robotiq_2f_85_gazebo_link_properties reference="${prefix}left_inner_knuckle" material="Gazebo/Black" />
    <xacro:robotiq_2f_85_gazebo_link_properties reference="${prefix}right_outer_knuckle" material="Gazebo/Grey" />
    <xacro:robotiq_2f_85_gazebo_link_properties reference="${prefix}right_outer_finger" material="Gazebo/Black" />
    <xacro:robotiq_2f_85_gazebo_link_properties reference="${prefix}right_inner_finger" material="Gazebo/Grey" />
    <xacro:robotiq_2f_85_gazebo_link_properties reference="${prefix}right_inner_knuckle" material="Gazebo/Black" />

    <xacro:macro name="robotiq_2f_85_gazebo_joint_properties" params="reference">
      <gazebo reference="${reference}">
        <implicitSpringDamper>true</implicitSpringDamper>
      </gazebo>
    </xacro:macro>

    <xacro:robotiq_2f_85_gazebo_joint_properties reference="${prefix}finger_joint"/>
    <xacro:robotiq_2f_85_gazebo_joint_properties reference="${prefix}left_outer_finger_joint"/>
    <xacro:robotiq_2f_85_gazebo_joint_properties reference="${prefix}left_inner_knuckle_joint"/>
    <xacro:robotiq_2f_85_gazebo_joint_properties reference="${prefix}left_inner_finger_joint"/>
    <xacro:robotiq_2f_85_gazebo_joint_properties reference="${prefix}right_finger_joint"/>
    <xacro:robotiq_2f_85_gazebo_joint_properties reference="${prefix}right_outer_finger_joint"/>
    <xacro:robotiq_2f_85_gazebo_joint_properties reference="${prefix}right_inner_knuckle_joint"/>
    <xacro:robotiq_2f_85_gazebo_joint_properties reference="${prefix}right_inner_finger_joint"/>

  </xacro:macro>
</robot>