# Define the goal
geometry_msgs/Pose pose  # desired pose
geometry_msgs/Pose offset # desired offset
geometry_msgs/Wrench wrench     # desired force and torque
string frame_id                # frame of pose

uint8 MODE_TARGET=0 # move towards target (offset adjusted to target)
uint8 MODE_OFFSET=1 # move with offset from current pose
uint8 mode 

---
# Define the result
---
# Define a feedback message
