<?xml version="1.0"?>

<robot name="pedestal_workspace" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="pedestal_workspace"
    params="pedestal_height:=0.2 pedestal_radius:=0.2">

    <link name="pedestal">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 ${-pedestal_height/2}" />
        <geometry>
          <cylinder length="${pedestal_height}" radius="${pedestal_radius}" />
        </geometry>
        <material name="grey">
          <color rgba=".5 .5 .5 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${-pedestal_height/2}" />
        <geometry>
          <cylinder length="${pedestal_height}" radius="${pedestal_radius}" />
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0.0 0.0 0.02" rpy="0 0 0" />
        <mass value=".006784" />
        <inertia ixx=".18e-05" iyy=".18e-05" izz=".18e-05" ixy="0.0" iyz="0.0" ixz="0.0" />
      </inertial>
    </link>

    <joint name="pedestal_to_world" type="fixed">
      <parent link="world" />
      <child link="pedestal" />
      <origin xyz="0 0 ${pedestal_height}" />
    </joint>
  </xacro:macro>

</robot>