[
  {frame_id: "tag_bundle_center", child_frame_id: "handle", x: -0.12, y: -0.222, z: 0.10, qx: -0.3535534, qy: 0.6123724, qz: 0.6123724, qw: 0.3535534},
  # {frame_id: "tag_31", child_frame_id: "latch_0_close", x: -0.02, y: -0.08, z: 0.025, qx: 0.5, qy: 0.5, qz: -0.5, qw: 0.5},
  # {frame_id: "tag_31", child_frame_id: "latch_0_open", x: -0.02, y: -0.08, z: 0.025, qx: 0.7071068, qy: 0.0, qz: -0.7071068, qw: 0.0},
  # {frame_id: "tool_a", child_frame_id: "tool_b", x: 0, y: 0.03, z: 0, qx: 0, qy: 0, qz: 0, qw: 1},
  # {frame_id: "tool_b", child_frame_id: "tool_c", x: 0, y: 0.03, z: 0, qx: 0, qy: 0, qz: 0, qw: 1},
  # {frame_id: "tool_c", child_frame_id: "tool_d", x: 0, y: 0.03, z: 0, qx: 0, qy: 0, qz: 0, qw: 1},
  # {frame_id: "tool_d", child_frame_id: "tool_e", x: 0, y: 0.03, z: 0, qx: 0, qy: 0, qz: 0, qw: 1},
  # {frame_id: "tool_e", child_frame_id: "tool_f", x: 0, y: 0.03, z: 0, qx: 0, qy: 0, qz: 0, qw: 1},
  # {frame_id: "robinzen_handle", child_frame_id: "robinzen_handle_grip", x: 0, y: 0, z: 0, qx: 0.5, qy: 0.5, qz: -0.5, qw: 0.5},
]