[
  {frame_id: "tag_bundle_center", child_frame_id: "handle", x: -0.12, y: -0.172, z: 0.10, qx: -0.3535534, qy: 0.6123724, qz: 0.6123724, qw: 0.3535534},
  # Latches in both open and closed position
  {frame_id: "tag_bundle_center", child_frame_id: "ru_latch_open", x: 0.165, y: -0.075, z: 0.01, qx: -0.5, qy: 0.5, qz: 0.5, qw: 0.5},
  {frame_id: "ru_latch_open", child_frame_id: "ru_latch_closed", x: 0.0, y: 0.0, z: 0.0, qx: -0.7071068, qy: 0, qz: 0, qw: 0.7071068},
  {frame_id: "tag_bundle_center", child_frame_id: "rl_latch_open", x: 0.17, y: -0.43, z: 0.01, qx: -0.5, qy: 0.5, qz: 0.5, qw: 0.5},
  {frame_id: "rl_latch_open", child_frame_id: "rl_latch_closed", x: 0.0, y: 0.0, z: 0.0, qx: 0.0, qy: 0, qz: 0.7071068, qw: 0.7071068},
    {frame_id: "tag_bundle_center", child_frame_id: "lu_latch_open", x: -0.375, y: -0.08, z: 0.01, qx: -0.5, qy: 0.5, qz: 0.5, qw: 0.5},
  {frame_id: "lu_latch_open", child_frame_id: "lu_latch_closed", x: 0.0, y: 0.0, z: 0.0, qx: 0.0, qy: 0, qz: 0.7071068, qw: 0.7071068},
    {frame_id: "tag_bundle_center", child_frame_id: "ll_latch_open", x: -0.375, y: -0.43, z: 0.01, qx: -0.5, qy: 0.5, qz: 0.5, qw: 0.5},
  {frame_id: "ll_latch_open", child_frame_id: "ll_latch_closed", x: 0.0, y: 0.0, z: 0.0, qx: 0.0, qy: 0, qz: 0.7071068, qw: 0.7071068},
  # tools on the tool rack
  {frame_id: "tools_bundle_center", child_frame_id: "tool_a", x: -0.085, y: 0.07, z: 0.04, qx: -0.5, qy: 0.5, qz: 0.5, qw: 0.5},
  {frame_id: "tools_bundle_center", child_frame_id: "tool_c", x: -0.01, y: 0.07, z: 0.04, qx: -0.5, qy: 0.5, qz: 0.5, qw: 0.5},
  {frame_id: "tools_bundle_center", child_frame_id: "tool_e", x: 0.07, y: 0.07, z: 0.06, qx: -0.5, qy: 0.5, qz: 0.5, qw: 0.5},
  # tool pallet handle and tool slots
  {frame_id: "pallet_center", child_frame_id: "pallet_handle", x: 0.0, y: 0.0, z: 0.0, qx: -0.5, qy: 0.5, qz: 0.5, qw: 0.5},
  {frame_id: "pallet_handle", child_frame_id: "pallet_tool_slot_l", x: 0.0, y: 0.04, z: 0.0, qx: 0, qy: 0, qz: 0, qw: 1.0},
  {frame_id: "pallet_handle", child_frame_id: "pallet_tool_slot_r", x: 0.0, y: -0.04, z: 0.0, qx: 0, qy: 0, qz: 0, qw: 1.0},
  # build plate
  {frame_id: "plate_bundle_center", child_frame_id: "plate_tab", x: 0.005, y: -0.136, z: 0.0, qx: -0.5, qy: -0.5, qz: 0.5, qw: 0.5},
  {frame_id: "plate_bundle_center", child_frame_id: "plate_metal_component", x: 0, y: 0, z: 0.025, qx: -0.2705981, qy: 0.2705981, qz: 0.6532815, qw: 0.6532815},

  # {frame_id: "tag_31", child_frame_id: "latch_0_close", x: -0.02, y: -0.08, z: 0.025, qx: 0.5, qy: 0.5, qz: -0.5, qw: 0.5},
  # {frame_id: "tag_31", child_frame_id: "latch_0_open", x: -0.02, y: -0.08, z: 0.025, qx: 0.7071068, qy: 0.0, qz: -0.7071068, qw: 0.0},
  # {frame_id: "tool_a", child_frame_id: "tool_b", x: 0, y: 0.03, z: 0, qx: 0, qy: 0, qz: 0, qw: 1},
  # {frame_id: "tool_b", child_frame_id: "tool_c", x: 0, y: 0.03, z: 0, qx: 0, qy: 0, qz: 0, qw: 1},
  # {frame_id: "tool_c", child_frame_id: "tool_d", x: 0, y: 0.03, z: 0, qx: 0, qy: 0, qz: 0, qw: 1},
  # {frame_id: "tool_d", child_frame_id: "tool_e", x: 0, y: 0.03, z: 0, qx: 0, qy: 0, qz: 0, qw: 1},
  # {frame_id: "tool_e", child_frame_id: "tool_f", x: 0, y: 0.03, z: 0, qx: 0, qy: 0, qz: 0, qw: 1},
  # {frame_id: "robinzen_handle", child_frame_id: "robinzen_handle_grip", x: 0, y: 0, z: 0, qx: 0.5, qy: 0.5, qz: -0.5, qw: 0.5},
]