# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    # {id: 1, size: 0.03},
    # {id: 2, size: 0.03},
    # {id: 3, size: 0.03},
    # {id: 4, size: 0.03},
    # {id: 5, size: 0.03},
    # {id: 6, size: 0.03},
    # {id: 7, size: 0.03},
    # {id: 8, size: 0.03},
    # {id: 9, size: 0.03},
    # {id: 10, size: 0.03},
    # {id: 11, size: 0.03},
    {id: 12, size: 0.03},
    {id: 13, size: 0.03},
    {id: 14, size: 0.03},
    {id: 15, size: 0.03},
    {id: 16, size: 0.03},
    {id: 17, size: 0.03},
    {id: 18, size: 0.03},
    {id: 19, size: 0.03},
    {id: 20, size: 0.03},
    {id: 21, size: 0.03},
    {id: 22, size: 0.03},
    {id: 23, size: 0.03},
    {id: 34, size: 0.08},
    {id: 35, size: 0.08},
]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [

    {
      name: 'plate_bundle_center',
      layout:
        [
          {id: 34, size: 0.08, x: -0.1675, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          {id: 35, size: 0.08, x: 0.1675, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
        ]
    },

    {
      name: 'tag_bundle_center',
      layout:
        [
          {id: 12, size: 0.03, x: -0.0225, y:  0.0225, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          {id: 13, size: 0.03, x:  0.0225, y:  0.0225, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          {id: 18, size: 0.03, x: -0.0225, y: -0.0225, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          {id: 19, size: 0.03, x:  0.0225, y: -0.0225, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
        ]
      },

    {
      name: 'tools_bundle_center',
      layout:
        [
          {id: 14, size: 0.03, x:  -0.1826, y:  0.0374, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          {id: 15, size: 0.03, x:  -0.1379, y:  0.0377, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          {id: 16, size: 0.03, x:   0.1670, y:  0.0455, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          {id: 17, size: 0.03, x:   0.2123, y:  0.0457, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          {id: 20, size: 0.03, x:  -0.0225, y: -0.0836, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          {id: 21, size: 0.03, x:   0.0225, y: -0.0827, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
        ]
      },

      {
      name: 'pallet_center',
      layout:
        [
          {id: 22, size: 0.03, x: -0.0225, y:  0.2, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          {id: 23, size: 0.03, x:  0.0225, y:  0.2, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
        ]
      },
    
  ]
