# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 1, size: 0.03},
    {id: 2, size: 0.03},
    {id: 3, size: 0.03},
    {id: 4, size: 0.03},
    {id: 5, size: 0.03},
    {id: 6, size: 0.03},
    {id: 7, size: 0.03},
    {id: 8, size: 0.03},
    {id: 9, size: 0.03},
    {id: 10, size: 0.03},
    {id: 11, size: 0.03},


  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'robinzen_handle',
      layout:
        [
          {id: 10, size: 0.03, x: -0.0225, y:  0.2, z: -0.1, qw: 1, qx: 0, qy: 0, qz: 0},
          {id: 11, size: 0.03, x: 0.0225, y:  0.2, z: -0.1, qw: 1, qx: 0, qy: 0, qz: 0},
        ]
      },
    {
      name: 'plate_tab',
      layout:
        [
          {id: 1, size: 0.03, x: 0.035, y: -0.1375, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          {id: 4, size: 0.03, x: 0.035, y: 0.1375, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          {id: 3, size: 0.03, x: 0.238, y: -0.1375, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
          {id: 2, size: 0.03, x: 0.238, y: 0.1375, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
        ]
    },
    {
      name: 'tool_a',
      layout:
        [
          {id: 5, size: 0.03, x: 0.045, y:  0.0245, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 7, size: 0.03, x: 0.045, y:  0.1035, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
          {id: 9, size: 0.03, x: 0.045, y:  0.1830, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
        ]
      },
    #   {
    #   name: 'tool_b',
    #   layout:
    #     [
    #       {id: 5, size: 0.03, x: 0.045, y:  -0.0150, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
    #       {id: 7, size: 0.03, x: 0.045, y:  0.0640, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
    #       {id: 9, size: 0.03, x: 0.045, y:  0.1435, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
    #     ]
    # },
    # {
    #   name: 'tool_c',
    #   layout:
    #     [
    #       {id: 5, size: 0.03, x: 0.045, y:  -0.0545, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
    #       {id: 7, size: 0.03, x: 0.045, y:  0.0245, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
    #       {id: 9, size: 0.03, x: 0.045, y:  0.1040, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
    #     ]
    # },
    # {
    #   name: 'tool_d',
    #   layout:
    #     [
    #       {id: 5, size: 0.03, x: 0.045, y:  -0.0940, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
    #       {id: 7, size: 0.03, x: 0.045, y:  -0.0150, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
    #       {id: 9, size: 0.03, x: 0.045, y:  0.0645, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
    #     ]
    # },
    # {
    #   name: 'tool_e',
    #   layout:
    #     [
    #       {id: 5, size: 0.03, x: 0.045, y:  -0.1335, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
    #       {id: 7, size: 0.03, x: 0.045, y:  -0.0545, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
    #       {id: 9, size: 0.03, x: 0.045, y:  0.0250, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
    #     ]
    # },
    # {
    #   name: 'tool_f',
    #   layout: 
    #     [
    #       {id: 5, size: 0.03, x: 0.045, y:  -0.1730, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
    #       {id: 7, size: 0.03, x: 0.045, y:  -0.0940, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
    #       {id: 9, size: 0.03, x: 0.045, y:  -0.0145, z: 0.0849, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5},
    #     ]
    # },
  ]
