name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        name: Check out code
    
      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v5.8
        with:
          image: repo/image
          tags: v1, latest
          registry: registry-url.io
          dockerfile: Dockerfile.ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
