name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

  - name: Docker Build & Push Action
    uses: mr-smithers-excellent/docker-build-push@v5.8
    with:
      image: thbarkouki/homestri-ur5e-robotiq2f85
      tag: latest
      registry: docker.io
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
